spring:
    data:
        mongodb:
            authentication-database: admin
            database: products-catalog
            uri: mongodb://${mongo.user}:${mongo.password}@${mongo.host}:${mongo.port}/${spring.data.mongodb.database}?authSource=${spring.data.mongodb.authentication-database}
            auto-index-creation: true
    main:
        allow-bean-definition-overriding: true
    mvc:
        problemdetails:
            enabled: true
    rabbitmq:
        host: ${RABBITMQ_HOST:localhost}
        port: ${RABBITMQ_PORT:5672}
        username: ${RABBITMQ_USER:guest}
        password: ${RABBITMQ_PASSWORD:guest}

mongo:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    user: ${MONGO_USER:mongoadmin}
    password: ${MONGO_PASSWORD:mongo}

rabbitmq:
    queue-name: ${RABBITMQ_NAME:catalog-emit}
    exchange: ${RABBITMQ_EXCHANGE:rabbit-exchange}
    routing-key: ${RABBITMQ_KEY:routing-key}

minio:
    host: ${MINIO_HOST:localhost}
    port: ${MINIO_PORT:9000}
    endpoint: http://${minio.host}:${minio.port}
    access-key: ${MINIO_ACCESS_KEY:minioadmin}
    secret-key: ${MINIO_SECRET_KEY:miniosecretkey}
    bucket-name: ${MINIO_BUCKET:bucket-catalog}
    file-size: 10485760
    secure: false